#############
### RULES ###
#############

# Example windowrule
windowrule = match:title ^(Alacritty)$, match:class ^(Alacritty)$, border_size 0
windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland on, match:fullscreen off, match:pin off, no_focus on
windowrule = match:class ^(firefox)$, opacity 1 override

# Windowrule for pavucontrol on special:settings
# Waybar height is 46
windowrule {
    name = pavucontrol-resizing
    match:class = ^(org.pulseaudio.pavucontrol)$

    workspace = special:settings
    float = on
    size = ((monitor_w-10)*0.5) (monitor_h-56)
    move = 5 46
}
# Windowrule for vpn (surfshark)
windowrule {
    name = vpn-resizing
    match:class = ^(.*Surfshark)$

    workspace = special:settings
    float = on
    size = ((monitor_w-10)*0.5) ((monitor_h-56)*0.5)
    move = ((monitor_w-10)*0.5) ((monitor_h+46)*0.5)
}
# Windowrule for bluetooth manager
windowrule {
    name = blueman-resizing
    match:class = ^(blueman-manager)$

    workspace = special:settings
    float = on
    size = (monitor_w-10)*0.5) ((monitor_h-56)*0.5)
    move = (monitor_w*0.5) 46
}
