format = """
$character\
$hostname\
$directory\
$git_status\
$git_branch\
"""

right_format = ""
add_newline = false
palette = "catppuccin_macchiato"
scan_timeout = 30
command_timeout = 500
follow_symlinks = true

[character] 
disabled = false
format = '[](teal) '

[directory]
disabled = false
format = '[$path]($style) '
style = 'teal'
read_only_style = 'maroon'
truncation_length = 1
truncation_symbol = ''

[git_branch]
disabled = false
format = '[git::\(](rosewater)[$branch(:$remote_branch)]($style)[\)](rosewater) '
style = 'pink'

[git_status]
disabled = false
format = '($style)([\[$conflicted$modified$untracked$staged\] ]($style))'
style = 'rosewater'

[hostname]
disabled = false
ssh_only = true
format = '[$hostname]($style) '
style = 'green'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
