##################
### WALLPAPERS ###
##################

$WALLPAPER_DIRECTORY = ~/.local/share/wallpapers
wallpaper {
    monitor = 
    path = $WALLPAPER_DIRECTORY/double_fish.jpg
    fit_mode = cover    
    timeout = 1
}
