set-option -g status-position bottom
set -g pane-border-status bottom

set -g status-style "bg=#{@thm_mantle}"
set -g status-justify "absolute-centre"
set -g focus-events on
set -g status-left-length 99
set -g status-right-length 99

set -g pane-border-format "[#S][#P]#{?pane_zoomed_flag,[Z]}"
set -g pane-active-border-style "bg=#{@thm_mantle},fg=#{@thm_lavender}"
set -g pane-border-style "bg=#{@thm_mantle},fg=#{@thm_surface_0}"
set -g pane-border-lines single

set -g window-status-format " #[fg=#{@thm_overlay_0}]#I"
set -g window-status-current-format " #{?client_prefix,#{#[fg=#{@thm_red},bold]#I},#{#[fg=#{@thm_mauve},bold]#I}}"

set -g status-left "#(cat #{socket_path}-\#{session_id}-vimbridge)"
set -g status-right "#(cat #{socket_path}-\#{session_id}-vimbridge-R)"
