monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "~alsa_card.*"
            }
        ]
        actions = {
            update-props = {
                api.alsa.soft-mixer = true
            }
        }
    }
]
